#指定端口号
server:
  port: 8001
log4j:
  debug: true
  rootLogger: debug, stdout


spring:
  application:
  #指定服务名称
    name: test-ribbon

eureka:
  client:
#  是否向注册中心获取服务这里我们通过两个注册中心互相注册，搭建了注册中心的双节点集群，由于defaultZone使用了域名，所以还需在本机的host文件中配置一下。
    fetch-registry: true
#  是否向注册中心注册
    register-with-eureka: true
    #默认注册中心URL,这里我们让他注册到两个注册中心上
    service-url:
      defaultZone: http://128.5.3.155:5000/eureka/,http://128.5.3.156:5000/eureka/

