
server:
  port: 5002
spring:
  application:
    name: Config
  profiles:
    active: subversion
  cloud:
    config:
      server:
        svn:
          uri: svn://zlyfs.synology.me/CorrectionSYS/configs
          username: zlyfs
          password: q1w2e3r4
          default-label:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
